application: wavecontroller
version: 2
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images

- url: .*
  script: main.py

